version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./src/app/Dockerfile.app
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src/app:/nrdp/src/app
    tty: true
    links: 
      - postgres
    networks: 
      - react-node-docker-postgres

  front:
    build:
      context: .
      dockerfile: ./src/front/Dockerfile.front
    ports:
     - "8080:8080"
    volumes:
      - ./src/front:/nrdp/src/front
    tty: true
    networks: 
      - react-node-docker-postgres

  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile.db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - react-node-docker-postgres

networks: 
    react-node-docker-postgres: