FROM node:12-alpine AS BUILD_IMAGE

WORKDIR /nrdp

COPY ./package*.json ./
RUN npm ci

COPY ./config ./config
COPY ./src/front ./src/front
RUN mkdir dist

ENV CHOKIDAR_USEPOLLING=true
EXPOSE 8080

CMD ["npm", "run", "front"]